-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_AdmissionApplication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "sessionId" TEXT NOT NULL,
    "familyId" TEXT,
    "studentId" TEXT,
    "applicantName" TEXT NOT NULL,
    "dateOfBirth" DATETIME,
    "gender" TEXT,
    "religion" TEXT,
    "category" TEXT,
    "aadhaar" TEXT,
    "apaarId" TEXT,
    "penId" TEXT,
    "srNo" TEXT,
    "appliedClassId" TEXT NOT NULL,
    "fatherName" TEXT,
    "fatherQualification" TEXT,
    "fatherOccupation" TEXT,
    "fatherDesignation" TEXT,
    "fatherAnnualIncome" DECIMAL,
    "fatherOfficeAddress" TEXT,
    "fatherPhone" TEXT,
    "fatherAadhaar" TEXT,
    "fatherEmail" TEXT,
    "motherName" TEXT,
    "motherQualification" TEXT,
    "motherIsWorking" BOOLEAN,
    "motherOccupation" TEXT,
    "motherDesignation" TEXT,
    "motherAnnualIncome" DECIMAL,
    "motherOfficeAddress" TEXT,
    "motherPhone" TEXT,
    "motherAadhaar" TEXT,
    "motherEmail" TEXT,
    "guardianName" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "resAddressLine1" TEXT,
    "resAddressLine2" TEXT,
    "resCity" TEXT,
    "resState" TEXT,
    "resPincode" TEXT,
    "sameAsResidential" BOOLEAN NOT NULL DEFAULT true,
    "permAddressLine1" TEXT,
    "permAddressLine2" TEXT,
    "permCity" TEXT,
    "permState" TEXT,
    "permPincode" TEXT,
    "previousSchoolName" TEXT,
    "previousClass" TEXT,
    "tcNumber" TEXT,
    "tcDate" DATETIME,
    "transportRequired" BOOLEAN NOT NULL DEFAULT false,
    "transportPickupPoint" TEXT,
    "declarationAccepted" BOOLEAN NOT NULL DEFAULT false,
    "declarationDate" DATETIME,
    "declarationParentName" TEXT,
    "admissionDate" DATETIME,
    "photoDocumentId" TEXT,
    "photoUrl" TEXT,
    "bloodGroup" TEXT,
    "fatherPhotoUrl" TEXT,
    "motherPhotoUrl" TEXT,
    "primaryPhoneBelongsTo" TEXT,
    "secondaryPhoneBelongsTo" TEXT,
    "fatherWhatsApp" TEXT,
    "motherWhatsApp" TEXT,
    "transportRoute" TEXT,
    "transportVehicle" TEXT,
    "transportDriver" TEXT,
    "transportDriverContact" TEXT,
    "previousBoard" TEXT,
    "previousReason" TEXT,
    "allergies" TEXT,
    "conditions" TEXT,
    "disability" TEXT,
    "emergencyRemarks" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "admissionNo" TEXT,
    "remarks" TEXT,
    "reviewedById" TEXT,
    "reviewedAt" DATETIME,
    CONSTRAINT "AdmissionApplication_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "AdmissionApplication_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "AcademicSession" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "AdmissionApplication_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "AdmissionApplication_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "AdmissionApplication_appliedClassId_fkey" FOREIGN KEY ("appliedClassId") REFERENCES "Class" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_AdmissionApplication" ("aadhaar", "address", "admissionDate", "admissionNo", "allergies", "apaarId", "applicantName", "appliedClassId", "bloodGroup", "category", "conditions", "createdAt", "dateOfBirth", "declarationAccepted", "declarationDate", "declarationParentName", "disability", "emergencyRemarks", "familyId", "fatherAadhaar", "fatherAnnualIncome", "fatherDesignation", "fatherEmail", "fatherName", "fatherOccupation", "fatherOfficeAddress", "fatherPhone", "fatherPhotoUrl", "fatherQualification", "fatherWhatsApp", "gender", "guardianName", "id", "motherAadhaar", "motherAnnualIncome", "motherDesignation", "motherEmail", "motherIsWorking", "motherName", "motherOccupation", "motherOfficeAddress", "motherPhone", "motherPhotoUrl", "motherQualification", "motherWhatsApp", "penId", "permAddressLine1", "permAddressLine2", "permCity", "permPincode", "permState", "phone", "photoDocumentId", "photoUrl", "previousBoard", "previousClass", "previousReason", "previousSchoolName", "primaryPhoneBelongsTo", "religion", "remarks", "resAddressLine1", "resAddressLine2", "resCity", "resPincode", "resState", "reviewedAt", "reviewedById", "sameAsResidential", "secondaryPhoneBelongsTo", "sessionId", "srNo", "status", "studentId", "tcDate", "tcNumber", "transportDriver", "transportDriverContact", "transportPickupPoint", "transportRequired", "transportRoute", "transportVehicle", "updatedAt") SELECT "aadhaar", "address", "admissionDate", "admissionNo", "allergies", "apaarId", "applicantName", "appliedClassId", "bloodGroup", "category", "conditions", "createdAt", "dateOfBirth", "declarationAccepted", "declarationDate", "declarationParentName", "disability", "emergencyRemarks", "familyId", "fatherAadhaar", "fatherAnnualIncome", "fatherDesignation", "fatherEmail", "fatherName", "fatherOccupation", "fatherOfficeAddress", "fatherPhone", "fatherPhotoUrl", "fatherQualification", "fatherWhatsApp", "gender", "guardianName", "id", "motherAadhaar", "motherAnnualIncome", "motherDesignation", "motherEmail", "motherIsWorking", "motherName", "motherOccupation", "motherOfficeAddress", "motherPhone", "motherPhotoUrl", "motherQualification", "motherWhatsApp", "penId", "permAddressLine1", "permAddressLine2", "permCity", "permPincode", "permState", "phone", "photoDocumentId", "photoUrl", "previousBoard", "previousClass", "previousReason", "previousSchoolName", "primaryPhoneBelongsTo", "religion", "remarks", "resAddressLine1", "resAddressLine2", "resCity", "resPincode", "resState", "reviewedAt", "reviewedById", "sameAsResidential", "secondaryPhoneBelongsTo", "sessionId", "srNo", "status", "studentId", "tcDate", "tcNumber", "transportDriver", "transportDriverContact", "transportPickupPoint", "transportRequired", "transportRoute", "transportVehicle", "updatedAt" FROM "AdmissionApplication";
DROP TABLE "AdmissionApplication";
ALTER TABLE "new_AdmissionApplication" RENAME TO "AdmissionApplication";
CREATE INDEX "AdmissionApplication_sessionId_status_idx" ON "AdmissionApplication"("sessionId", "status");
CREATE INDEX "AdmissionApplication_admissionNo_idx" ON "AdmissionApplication"("admissionNo");
CREATE TABLE "new_Student" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "schoolId" TEXT NOT NULL,
    "familyId" TEXT NOT NULL,
    "admissionNo" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "middleName" TEXT,
    "lastName" TEXT,
    "fullName" TEXT NOT NULL,
    "dateOfBirth" DATETIME,
    "gender" TEXT,
    "bloodGroup" TEXT,
    "aadhaar" TEXT,
    "religion" TEXT,
    "category" TEXT,
    "apaarId" TEXT,
    "penId" TEXT,
    "srNo" TEXT,
    "previousSchoolName" TEXT,
    "previousClass" TEXT,
    "tcNumber" TEXT,
    "tcDate" DATETIME,
    "transportRequired" BOOLEAN NOT NULL DEFAULT false,
    "transportPickupPoint" TEXT,
    "admissionDate" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "photoDocumentId" TEXT,
    "photoUrl" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "transportRoute" TEXT,
    "transportVehicle" TEXT,
    "transportDriver" TEXT,
    "transportDriverContact" TEXT,
    "previousBoard" TEXT,
    "previousReason" TEXT,
    CONSTRAINT "Student_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Student_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_Student" ("aadhaar", "admissionDate", "admissionNo", "apaarId", "bloodGroup", "category", "createdAt", "dateOfBirth", "familyId", "firstName", "fullName", "gender", "id", "lastName", "middleName", "penId", "photoDocumentId", "photoUrl", "previousBoard", "previousClass", "previousReason", "previousSchoolName", "religion", "schoolId", "srNo", "status", "tcDate", "tcNumber", "transportDriver", "transportDriverContact", "transportPickupPoint", "transportRequired", "transportRoute", "transportVehicle", "updatedAt") SELECT "aadhaar", "admissionDate", "admissionNo", "apaarId", "bloodGroup", "category", "createdAt", "dateOfBirth", "familyId", "firstName", "fullName", "gender", "id", "lastName", "middleName", "penId", "photoDocumentId", "photoUrl", "previousBoard", "previousClass", "previousReason", "previousSchoolName", "religion", "schoolId", "srNo", "status", "tcDate", "tcNumber", "transportDriver", "transportDriverContact", "transportPickupPoint", "transportRequired", "transportRoute", "transportVehicle", "updatedAt" FROM "Student";
DROP TABLE "Student";
ALTER TABLE "new_Student" RENAME TO "Student";
CREATE INDEX "Student_schoolId_fullName_idx" ON "Student"("schoolId", "fullName");
CREATE INDEX "Student_familyId_idx" ON "Student"("familyId");
CREATE INDEX "Student_schoolId_status_idx" ON "Student"("schoolId", "status");
CREATE UNIQUE INDEX "Student_schoolId_admissionNo_key" ON "Student"("schoolId", "admissionNo");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
